### PR TITLE
FEATURE: Add per-reaction score awarding

### PR DESCRIPTION
**Pull request by rngus2344**
Now giving and receiving reactions award users per-reaction score:

Screenshot 2023-06-07 at 1 56 18 PM

Screenshot 2023-06-07 at 1 55 09 PM

Screenshot 2023-06-07 at 1 56 50 PM

### CODE REVIEW

**Comment by xfalcox** [comment]
AFAIK the default reaction also creates a like, so it's double counting both likes and reactions here? Not sure we can do something about it tho.

**Comment by rngus2344** [comment]
> AFAIK the default reaction also creates a like, so it's double counting both likes and reactions here? Not sure we can do something about it tho.

When I checked it, default reaction was only counted as a like not as reaction. I will double-check it and let you know.

**Comment by rngus2344** [comment]
When I do default reaction, it creates 'like' and stored in ```post_actions```:
Screenshot 2023-06-07 at 2 27 33 PM

But it is not stored in ```discourse_reactions_reaction_users```: 
Screenshot 2023-06-07 at 2 27 00 PM

(The ```post_id``` 87 is where I did 'like')
Is it correct? Please let me know if I am missing something.

**Review by xfalcox — APPROVED** [review]

**Comment by rngus2344** [comment]
Now giving and receiving reactions award users per-reaction score.

**Pull request merged**
